/*
 * 字符串中有几个 A
 */
package contest.lanqiao.模拟题2022.t1;

public class Main {

    public static void main(String[] args) {
        String[] ss = { "AAAAAAABABBAABABABAAAAAAA", "ABBBBBABBAABBBBBABABBBBBA", "ABAAABABBBABAABBBBABAAABA",
                "ABAAABABBBBBAABAABABAAABA", "ABAAABABBABABBABABABAAABA", "ABBBBBABBBABAABBBBABBBBBA",
                "AAAAAAABABABABABABAAAAAAA", "BBBBBBBBABAABABBBBBBBBBBB", "AABAABABBAAABBAAABABBBBBA",
                "ABBABABBBABBAAAABBBBAAAAB", "BBBBAAABABAABABAABBBAABBA", "BBAABABABAAAABBBAABBAAAAA",
                "ABABBBABAABAABABABABBBBBA", "AAAABBBBBABBBBAAABBBABBAB", "AABAABAAABAAABAABABABAAAA",
                "ABBBBBBBBABABBBBABAABBABA", "ABBBAAABAAABBBAAAAAAABAAB", "BBBBBBBBABBAAABAABBBABBAB",
                "AAAAAAABBAAABBBBABABAABBA", "ABBBBBABBAABABAAABBBABBAA", "ABAAABABABBBAAAAAAAAAABAA",
                "ABAAABABABABBBABBAABBABAA", "ABAAABABBABBABABAABAABAAA", "ABBBBBABABBBBBABBAAAABAAA",
                "AAAAAAABAABBBAABABABBABBA" };
        int num = 0;
        for(String s : ss) {
            for(char c:s.toCharArray()) {
                if(c == 'A') {
                    num++;
                }
            }
        }
        System.out.println(num);
    }

}
